### ISSUE TITLE
Inference Service cannot be reached if used with an Application Gateway + WAF

### ISSUE THREAD

**Issue by ant0nsc** [microsoft/InnerEye-Inference#37]

**Comment by peterhessey** [comment]
**_WIP comment: some rules may still need to be adjusted!_**

The Web Application Firewall contains rules that prevent requests from the InnerEye Gateway reaching the Inference App Service. These rules can be selectively deactivated to enable requests to pass uninhibited. To rectify this, follow these steps:

* Navigate to your WAF in your Application Gateway
* Select "Rules"
* Ensure "Advanced Rule Configuration" is enabled

![Image](https://user-images.githubusercontent.com/45258028/177368687-45a4b455-cb37-4d8b-aa24-3b086a8ab6a1.png)

* Under "REQUEST-920-PROTOCOL-ENFORCEMENT" deactivate the following rules:
    * 920300 (Request Missing an Accept Header)
    * 920310 (Request Has an Empty Accept Header)
    * 920311 (Request Has an Empty Accept Header)
    * 920320 (Missing User Agent Header)
    * 920340 (Request Containing Content, but Missing Content-Type header)
    * 920350 (Host header is a numeric IP address)

![Image](https://user-images.githubusercontent.com/45258028/177369107-9f5b2f95-1aac-4c10-b9e8-356e91d7d561.png)

* Select save
* Wait ~30 minutes for the WAF to update. Your Gateway should now be able to interact with the Inference App Service.

**Comment by peterhessey** [comment]
This has been fixed by [changes to the InnerEye Gateway](https://github.com/microsoft/InnerEye-Gateway/pull/109)
